# Generated by Django 3.0.1 on 2020-01-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Név')),
                ('profile_pic', models.ImageField(upload_to='about', verbose_name='Profilkép')),
                ('faceebook', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('phone', models.CharField(blank=True, max_length=200, verbose_name='Telefon')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Magamról',
            },
        ),
    ]
